Add rule for making mad.pc

--- a/Makefile.am
+++ b/Makefile.am
@@ -130,6 +130,9 @@
 	echo '}';  \
 	echo "# endif") >$@
 
+mad.pc: $(top_builddir)/config.status mad.pc.in
+	cd $(top_builddir) && CONFIG_FILES=$@ CONFIG_HEADERS= $(SHELL) ./config.status
+
 libtool: $(LIBTOOL_DEPS)
 	$(SHELL) ./config.status --recheck
 
