/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"wz_repo_for_builds"
#define VCS_BRANCH		""
#define VCS_TAG			"3.2.3"
#define VCS_EXTRA       "3.2.3"


#define VCS_FULL_HASH		"c84d1934d6d087c5a37d978207acc2409d354c3b"
#define VCS_SHORT_HASH		"c84d193"

#define VCS_WC_MODIFIED		0

#endif

/* end */
